apiVersion: v2
name: opengist
description: Opengist Helm chart for Kubernetes
type: application
version: 0.5.0
appVersion: 1.12.0
home: https://opengist.io
icon: https://raw.githubusercontent.com/thomiceli/opengist/master/public/img/opengist.svg
sources:
  - https://github.com/thomiceli/opengist
dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.7.27
    condition: postgresql.enabled
  - name: meilisearch
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    version: 0.17.1
    condition: meilisearch.enabled
